
create table
  public.events (
    event_id integer generated by default as identity not null,
    event_name text not null,
    event_date date not null,
    venue text not null,
    attendance integer null,
    constraint events_pkey primary key (event_id)
  ) tablespace pg_default;

create table
  public.fighter_stats (
    stats_id bigint generated by default as identity not null,
    kd smallint null default '0'::smallint,
    strikes smallint null default '0'::smallint,
    td smallint null default '0'::smallint,
    sub smallint null default '0'::smallint,
    weight smallint null,
    constraint fighter_stats_pkey primary key (stats_id),
    constraint fighter_stats_stats_id_key unique (stats_id)
  ) tablespace pg_default;

  create table
  public.fighters (
    fighter_id integer generated always as identity not null,
    first_name text null,
    last_name text null,
    height smallint null,
    reach numeric(3, 1) null,
    stance smallint null,
    constraint fighters_pkey primary key (fighter_id),
    constraint fighters_stance_fkey foreign key (stance) references stances (id)
  ) tablespace pg_default;

  create table
  public.fights (
    fight_id integer generated always as identity not null,
    fighter1_id integer null,
    fighter2_id integer null,
    round_num smallint null,
    round_time text not null,
    event_id integer null,
    result integer null,
    stats_1 bigint null,
    stats_2 bigint null,
    method_of_vic smallint null,
    constraint fights_pkey primary key (fight_id),
    constraint fights_fighter1_id_fkey foreign key (fighter1_id) references fighters (fighter_id),
    constraint fights_fighter2_id_fkey foreign key (fighter2_id) references fighters (fighter_id),
    constraint fights_event_id_fkey foreign key (event_id) references events (event_id),
    constraint fights_stats_1_fkey foreign key (stats_1) references fighter_stats (stats_id),
    constraint fights_stats_2_fkey foreign key (stats_2) references fighter_stats (stats_id),
    constraint fights_method_of_vic_fkey foreign key (method_of_vic) references victory_methods (id)
  ) tablespace pg_default;

 create table
  public.stances (
    id smallint generated by default as identity not null,
    stance text null,
    constraint stances_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.victory_methods (
    id smallint generated by default as identity not null,
    method text null,
    constraint victory_methods_pkey primary key (id)
  ) tablespace pg_default;